#!/usr/bin/env tclsh
# Delegates to the demo that builds cheat sheets
source [file join [file dirname [info script]] ../_bootstrap.tcl]
pdf4tcl::doc::init [info script]
set demo [file join $::pdf4tcl::doc::reporoot 0.9.4.x demo demo-make-cheatsheets.tcl]
puts "Running $demo ..."
set rc [catch {exec [info nameofexecutable] $demo 2>@1} out]
puts $out
if {$rc} { exit 1 }
# copy note
puts "Cheat sheets are under 0.9.4.x/demo/out/ (see howto-cheatsheets.md)"
# also drop a pointer PDF in doc out
set pdf [::pdf4tcl::new %AUTO% -paper a4 -orient 1 -margin 50]
$pdf startPage
$pdf setFont 12 Helvetica
$pdf text "Cheat sheets generated by demo-make-cheatsheets.tcl" -x 0 -y 40
$pdf text "See 0.9.4.x/demo/out/" -x 0 -y 60
$pdf endPage
set out [pdf4tcl::doc::outfile howto-cheatsheets-pointer.pdf]
$pdf write -file $out
$pdf destroy
pdf4tcl::doc::done $out
