#!/usr/bin/env tclsh
# mk-stdkern.tcl -- kern pairs of the standard 14, from the AFM files.
#
#   tclsh tools/mk-stdkern.tcl afm stdkern.tcl
#
# Writes stdkern.tcl in the same shape as stdmetrics.tcl: the values sit
# under BFA(<font>,kernPairs), keyed by UNICODE pairs rather than by glyph
# names, so they match charWidths and GetKernPair can use them as they are.
#
# Not tools/extract-metrics.tcl, which writes a different format
# (font_widths, keyed by glyph name) and whose Makefile line has been
# commented out for years.
#
# AFM values are already in 1/1000 em, unlike a TrueType kern table, where
# they are in font units and need unitsPerEm.

set afmdir [expr {$argc > 0 ? [lindex $argv 0] : "afm"}]
set ziel   [expr {$argc > 1 ? [lindex $argv 1] : "stdkern.tcl"}]

set here [file dirname [file normalize [info script]]]
source [file join $here .. glyph2uni.tcl]

# GlName2Uni is an ARRAY, not a dict.
proc uni {name} {
    if {[info exists ::pdf4tcl::GlName2Uni($name)]} {
        return $::pdf4tcl::GlName2Uni($name)
    }
    return ""
}

set alle [dict create]
set ohneName [dict create]

foreach datei [lsort [glob -nocomplain [file join $afmdir *.afm]]] {
    set f [open $datei r]
    set fontname ""
    set paare [dict create]
    set inMetrics 0
    while {[gets $f zeile] != -1} {
        if {[regexp {^FontName\s+(\S+)} $zeile -> n]} { set fontname $n }
        if {[regexp {^StartCharMetrics} $zeile]} { set inMetrics 1; continue }
        if {[regexp {^EndCharMetrics} $zeile]}   { set inMetrics 0; continue }
        if {$inMetrics} { continue }
        # KPX <left> <right> <value>
        if {![regexp {^KPX\s+(\S+)\s+(\S+)\s+(-?\d+)} $zeile -> l r w]} { continue }
        if {$w == 0} { continue }
        set lu [uni $l]
        set ru [uni $r]
        if {$lu eq "" || $ru eq ""} {
            # A glyph name with no Unicode equivalent: skipped and
            # counted. Better one pair less than one in the wrong place.
            dict incr ohneName $l
            continue
        }
        dict set paare $lu,$ru $w
    }
    close $f
    if {$fontname eq "" || ![dict size $paare]} {
        puts [format "  %-24s no pairs" [file tail $datei]]
        continue
    }
    dict set alle $fontname $paare
    puts [format "  %-24s %s pairs" $fontname [dict size $paare]]
}

set ch [open $ziel w]
puts $ch "package provide pdf4tcl::stdkern 0.1"
puts $ch ""
puts $ch "# this file is auto-generated by tools/mk-stdkern.tcl, do NOT edit!"
puts $ch "#"
puts $ch "# Pair kerning of the standard 14, taken from the Adobe AFM files."
puts $ch "# Keys are UNICODE pairs, matching BFA(<font>,charWidths); the"
puts $ch "# values are already in 1/1000 em, as AFM measures."
puts $ch ""
puts $ch "namespace eval pdf4tcl {"
puts $ch "variable BFA"
puts $ch ""
foreach fontname [lsort -dictionary [dict keys $alle]] {
    set paare [dict get $alle $fontname]
    set flach {}
    foreach schluessel [lsort [dict keys $paare]] {
        lappend flach $schluessel [dict get $paare $schluessel]
    }
    puts $ch [list set BFA($fontname,kernPairs) $flach]
}
puts $ch "}"
close $ch

puts ""
puts "  written: $ziel ([file size $ziel] Bytes)"
if {[dict size $ohneName]} {
    puts "  skipped, no Unicode equivalent: [dict size $ohneName] glyph names"
    puts "    [lrange [lsort [dict keys $ohneName]] 0 5] ..."
}
